BEGIN TRANSACTION;
CREATE TABLE gifts (
	id INTEGER NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	"desc" VARCHAR(250), 
	link VARCHAR(250), 
	image VARCHAR(250), 
	status VARCHAR(10), 
	date_added DATE NOT NULL, 
	date_given DATE, 
	giver_id INTEGER, 
	rec_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(giver_id) REFERENCES givers (id), 
	FOREIGN KEY(rec_id) REFERENCES recipients (id)
);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (1,'A good night''s sleep','What every parent and child wants!','http://www.dreamaway.com','http://www.rezabavar.com/wp-content/uploads/2010/06/Sleep.jpg','idea','2016-01-07',NULL,1,3);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (2,'Fiorentina  Scarf','Oversized Plaid Scarf with Fringe','http://www.amazon.com/Fiorentina-Womens-Oversized-Plaid-Fringe/dp/B00TV4CF36/ref=sr_1_7','http://cdn.saleoffaccessories.com/d1/fc/d1fc1373d0e5e01ae234dd2c222b4468/la-fiorentina-plush-plaid-fringe-scarf.jpg','idea','2016-01-08',NULL,1,1);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (3,'What to Expect When You''re Expecting','America''s pregnancy bible','http://www.amazon.com/What-Expect-When-Youre-Expecting/dp/0761148574/ref=sr_1_1','https://upload.wikimedia.org/wikipedia/en/d/d6/What_to_Expect_When_You''re_Expecting_Cover.jpg','idea','2016-01-08',NULL,1,1);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (6,'Mama Bee Belly Butter','Burt''s Bees Belly Butter, 6.5 Ounce','http://www.amazon.com/gp/product/B00DM14TYC/ref=s9_simh_gw_p14_d0_i5','http://www.allbabyforbaby.com/image/cache/data/burts-bees/burts-bees-mama-bee-belly-butter-6-5-ounce-2-500x500.jpg','given','2016-01-08','2016-01-08',1,1);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (7,'Total Body Pillow','Supports hips, back, neck, and tummy','http://www.amazon.com/gp/product/B0000635WI/ref=s9_simh_gw_p121_d0_i3','http://s7d9.scene7.com/is/image/BedBathandBeyond/8000415038357p','idea','2016-01-08',NULL,1,1);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (10,'A good night''s sleep','What every parent and child wants!','http://www.dreamaway.com','http://www.rezabavar.com/wp-content/uploads/2010/06/Sleep.jpg','purchased','2016-01-09',NULL,1,1);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (13,'WubbaNub Brown Monkey','Pacifier attached permanently to stuffed animal','http://www.amazon.com/WubbaNub-WN22330-Brown-Monkey/dp/B0028IDXDS/ref=sr_1_12','http://ecx.images-amazon.com/images/I/712ym48jIHL._SX522_.jpg','idea','2016-01-09',NULL,1,3);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (14,'Baby Sling Carrier','For babies from birth to 50 lbs','http://www.amazon.com/Original--Fashion-Comfortable-Innoo-Tech/dp/B0156HL9WE/ref=sr_1_4','https://images-na.ssl-images-amazon.com/images/I/41QZfy9IkAL.jpg','purchased','2016-01-09',NULL,1,1);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (15,'Transforming High Chair','Use it all your life!','http://www.amazon.com/Abiie-Perfect-Highchair-Solution-Toddlers/dp/B00BSD7PMY/','http://ecx.images-amazon.com/images/I/81hq-8nUxQL._SL1500_.jpg','idea','2016-01-09',NULL,1,3);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (17,'Beau Gâchis Makeup Brushes','7 Piece Make up Brush Set Kit with Holder','http://www.amazon.com/Beau-G%C3%A2chis%C2%AE-Paris-Brushes-Natural/dp/B00HO2XYEQ','http://ecx.images-amazon.com/images/I/61Ja42kx7pL._SX522_.jpg','idea','2016-01-11',NULL,1,9);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (18,'A good night''s sleep','What every parent and child wants!','http://www.dreamaway.com','http://www.rezabavar.com/wp-content/uploads/2010/06/Sleep.jpg','idea','2016-01-11',NULL,1,9);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (21,'Knuffle Bunny','Luxuriously soft velour bean filled body','http://www.amazon.com/YOTTOY-502-Knuffle-Bunny12-25/dp/B001BRFFAQ','http://ecx.images-amazon.com/images/I/51whZ9w-4GL._SX425_.jpg','idea','2016-01-11',NULL,1,8);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (22,'A good night''s sleep','What every parent and child wants!','http://www.dreamaway.com','http://www.rezabavar.com/wp-content/uploads/2010/06/Sleep.jpg','idea','2016-01-11',NULL,1,4);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (23,'Knuffle Bunny','Luxuriously soft velour bean filled body','http://www.amazon.com/YOTTOY-502-Knuffle-Bunny12-25/dp/B001BRFFAQ','http://ecx.images-amazon.com/images/I/51whZ9w-4GL._SX425_.jpg','idea','2016-01-11',NULL,1,3);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (24,'Fighting Irish Sweater','Kelly Green ND Logo','http://www.ladyfanatics.com/league/College/team/Notre_Dame_Fighting_Irish/category/8137/browse/featuredproduct/1748283/partnerid/13885/source/GPA_CA-LF?sku=5749968','','idea','2016-01-13',NULL,1,9);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (25,'Fighting Irish Navy Cardigan','"Colosseum" style, V-neck with two pockets','http://www.fansedge.com/league/College/team/Notre_Dame_Fighting_Irish/category/3103/browse/featuredproduct/2025230/partnerid/14071/source/csefe12-pla-id?sku=6597898&utm_content=TEST&gclid=CI396aCEp8oCFU4WHwod-CICiw','http://fansedge.frgimages.com/FFImage/thumb.aspx?i=/productImages/_2025000/ff_2025230_xl.jpg&w=500','idea','2016-01-13',NULL,1,10);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (26,'A good night''s sleep','What every parent and child wants!','http://www.dreamaway.com','http://www.rezabavar.com/wp-content/uploads/2010/06/Sleep.jpg','idea','2016-01-13',NULL,1,5);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (27,'Rocket Pogo Stick','Foam covered metal frame, Non slip foot pads','http://www.amazon.com/Flybar-Chrome-Rocket-Pogo-Stick/dp/B00XAJ22UO','http://c.shld.net/rpx/i/s/pi/mp/27954/prod_3316190121?src=http%3A%2F%2Fcp75.com%2FABS%2FImages%2F31ckOoF4GGL._SS400_.jpg&d=5569f97370c33c13b33e9cceddf160f7a33903a4&hei=245&wid=245&op_sharpen=1&qlt=85','idea','2016-01-13',NULL,3,11);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (28,'100-Piece Wooden Block Set','Variety of shapes: rectangular prisms, cubes, cylinders, half circles, arches, rectangular planks and triangles.','http://www.amazon.com/Melissa-Doug-100-Piece-Wood-Blocks/dp/B000068CKY','http://www.brightbeans.co.za/images/detailed/1/Melissa&Doug_100_Piece_Wood_Block_Set_2137510294751f667e397fb2.png','purchased','2016-01-13',NULL,3,11);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (29,'Blue Acoustic Guitar','38 inch body, and blue!','http://www.amazon.com/Acoustic-Starter-Beginner-DirectlyCheap-Translucent/dp/B006CYVD5E','http://ecx.images-amazon.com/images/I/41lCP%2BMck3L.jpg','idea','2016-01-13',NULL,3,11);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (30,'Adventure Science: Chemistry Blast','Young Scientists create sticky ice, remove gas from soda, and make flower change colors. Young Scientists use test tubes, filter paper, and funnel to separate mixture of materials and making an explosion that will excite any budding scientist','http://www.amazon.com/Adventure-Science-series-Chemistry-Blast/dp/B000E9TBNO','http://ecx.images-amazon.com/images/I/81IVMXCDl-S._SX425_.jpg','idea','2016-01-13',NULL,3,12);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (31,'Classic Mini Djembe Drum','Desktop Djembe, perfect drum for small children, classrooms, or lunchtime jams; 4in Playing Surface, 8in Height','http://www.amazon.com/Africa-Heartwood-Project-SD4X8-Classic/dp/B006CQ8PGC','http://ecx.images-amazon.com/images/I/41L2Qz3u23L._SY355_.jpg','purchased','2016-01-13',NULL,3,12);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (32,'KPC Pro Skateboard Complete','Canadian Maple Construction; 7.75-Inch Deck','http://www.amazon.com/KPC-Skateboard-Complete-Black-Checker/dp/B004UOL6BO','http://ecx.images-amazon.com/images/I/41curokU5dL._SY355_.jpg','idea','2016-01-13',NULL,3,12);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (33,'Mini Bass Guitar','Pink; Only 31.5inch overall length (smallest bass guitar on the market)','http://www.amazon.com/MB1-Quality-small-guitar-travel/dp/B00Q9TBWTE','http://ecx.images-amazon.com/images/I/41DK-PhwBGL.jpg','idea','2016-01-13',NULL,3,13);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (34,'Razor A2 Kick Scooter','Made of sturdy aircraft-grade aluminum with red highlights','http://www.amazon.com/Razor-A2-Kick-Scooter-Red/dp/B00005MOYK','http://www.toysrus.com/graphics/product_images/pTRU1-3029018dt.jpg','idea','2016-01-13',NULL,3,13);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (35,'WubbaNub Brown Monkey','Pacifier attached permanently to stuffed animal','http://www.amazon.com/WubbaNub-WN22330-Brown-Monkey/dp/B0028IDXDS','http://ecx.images-amazon.com/images/I/712ym48jIHL._SX522_.jpg','purchased','2016-01-13',NULL,4,16);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (36,'Transforming High Chair','Chair adjusts as your child ages.','http://www.amazon.com/Abiie-Perfect-Highchair-Solution-Toddlers/dp/B00BSD7PMY/','http://ecx.images-amazon.com/images/I/81hq-8nUxQL._SL1500_.jpg','idea','2016-01-13',NULL,4,16);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (37,'Junior Toy Saxophone','The Bontempi Junior Saxophone offers 4 colored keys/notes','http://www.amazon.com/Junior-Toy-Saxophone-by-Bontempi','http://ecx.images-amazon.com/images/I/51fxtTaDF9L._SY355_.jpg','purchased','2016-01-13',NULL,4,15);
INSERT INTO `gifts` (id,name,desc,link,image,status,date_added,date_given,giver_id,rec_id) VALUES (38,'Creativity for Kids Butterfly Necklaces','Create 6 beautiful butterfly necklaces','http://www.amazon.com/Creativity-for-Kids-Butterfly-Necklaces/dp/B00BUSZ1I2','http://cdn3.bigcommerce.com/s-ovsa8in/products/10623/images/13340/TNW-560274-2__06359.1440331991.650.650.jpg?c=2','idea','2016-01-13',NULL,4,15);
COMMIT;
